# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x04\x66ile\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x11ListFilesResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\"\x07\n\x05\x45mpty\"5\n\x10ReplicateRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"$\n\x11ReplicateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x84\x01\n\x0b\x46ileService\x12\x31\n\tListFiles\x12\x0b.file.Empty\x1a\x17.file.ListFilesResponse\x12\x42\n\rReplicateFile\x12\x16.file.ReplicateRequest\x1a\x17.file.ReplicateResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=20
  _globals['_FILECHUNK']._serialized_end=48
  _globals['_DOWNLOADREQUEST']._serialized_start=50
  _globals['_DOWNLOADREQUEST']._serialized_end=85
  _globals['_UPLOADRESPONSE']._serialized_start=87
  _globals['_UPLOADRESPONSE']._serialized_end=120
  _globals['_LISTFILESRESPONSE']._serialized_start=122
  _globals['_LISTFILESRESPONSE']._serialized_end=160
  _globals['_EMPTY']._serialized_start=162
  _globals['_EMPTY']._serialized_end=169
  _globals['_REPLICATEREQUEST']._serialized_start=171
  _globals['_REPLICATEREQUEST']._serialized_end=224
  _globals['_REPLICATERESPONSE']._serialized_start=226
  _globals['_REPLICATERESPONSE']._serialized_end=262
  _globals['_FILESERVICE']._serialized_start=265
  _globals['_FILESERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
